@extends('web.includes.master')
@section('title', 'Privacy Policy')
@section('content')

<section class="pad-top-60 pad-bot-60">
   <div class="container">
      <div class="sec-head1">
         <h3>{{ __('content.Privacy Policy') }} </h3>
      </div>
      <div class="privacy-policy-content">
         <div>
            <h4 class="col-black">{{ __('content.INTRODUCTION') }} </h4>
            <p>{{ __('content.Thank you for visiting') }} <a href="#"> www.micahha.com </a>{{ __('content.including any related web pages, content, functionality and services offered thereon (the "Website"), which is operated by International Fashion Brands Pty Ltd (ABN: 66 602 721 488) and its related companies (“Micahha”, “SMCP”, “we”, “us”, “our”) Sandro understands that your privacy is important and ensures that your personal information is handled in accordance with the Privacy Act 1988 (Cth) (Privacy Act), and GDPR.') }} </p>
            <p>{{ __('content.We are the primary data controller for the purposes of this website and our registered head office is located at Suite 301, 30-36 Bay Street, Double Bay NSW 2028, Australia.') }} </p>
            <p>{{ __('content.Any changes we make to this policy in the future will be posted on this page and, if appropriate, notified to you by email so please check this page regularly.') }} </p>
            <p>{{ __('content.Last updated 07/03/2019.') }} </p>
            <p>{{ __('content.This privacy policy (the "Privacy Policy") should be read together with, and is incorporated by reference into, the Website terms of use (the "Terms of Use").') }} </p>
            <p>{{ __('content.This Privacy Policy describes the types of personal information we may collect from you when you visit our Website or our stores, how we use and protect this information, and when we share it with third parties or affiliates, among other things. This Privacy Policy does not apply to information collected on any other website or application, such as those operated by a third party or, except as otherwise disclosed herein, any affiliate or subsidiary of the Company, that may link to, or be accessible from, the Website. See "Links to Other Websites " below.') }} </p>
            <p>{{ __('content.By accessing or using the Website, you acknowledge, understand and agree to be bound by the terms of this Privacy Policy and you consent to the collection and use by Sandro of the information about you as described herein. Please do not submit your personal information if you do not want it to be collected, used, and disclosed as described in the Privacy Policy.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.INTENDED USERS') }} </h4>
            <p>{{ __('content.This Website is hosted in the United States and operated in Australia, pursuant to the applicable laws in Australia, and is only intended for users who are located in Australia or New Zealand. By providing personal information through the use of this Website, you understand and consent to the collection, maintenance, processing and transfer of such information in and to Australia and waive any claims that may arise under applicable foreign laws.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.MODIFICATIONS TO PRIVACY POLICY') }} </h4>
            <p>{{ __('content.The information on this Website and our Privacy Policy are subject to change from time to time in our sole discretion. You will be notified of any material changes to our Privacy Policy on this page under "Last Update ", below. Your continued use of the Website on or after the date of any such changes or update(s) shall constitute your agreement to any such updated Privacy Policy. We therefore encourage you to refer to this policy on an ongoing basis so that you understand our current Privacy Policy.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.LAST UPDATE') }} </h4>
            <p>{{ __('content.Our policy was last updated on March 7, 2019.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.WHAT INFORMATION DOES SANDRO COLLECT?') }} </h4>
            <p>{{ __('content.Sandro collects data that you voluntarily provide on the Website through transactions, user registration on the Website, surveys, sweepstakes, or contests; that you provide to our sales associates in our Company-owned or affiliated stores; or through phone, e-mail, mail and fax interactions or paper registrations that you submit to us. In the event we conduct surveys or run a contest or sweepstakes, a set of rules or terms governing the survey, contest or sweepstakes will be provided please read such rules carefully before participating in or entering any survey, contest or sweepstakes relating to this Website.') }} </p>
            <p>{{ __('content.Sandro may collect and store two types of information: "personal information" and "automatic information."') }}  </p>
            <p>{{ __('content."Personal information " is personally identifiable information about you including, but not limited to, your name, gender, billing address, shipping address, email address, telephone number, date of birth or age, any personal preferences you choose to provide, transaction details such as style, size, price, discount, date, store, and an assigned password to protect your privacy.') }} </p>
            <p>{{ __('content."Automatic information" is information that we collect automatically whenever you interact with this Website, such as your IP address, the type of computer you use, and the web browser you use. An IP address is a number assigned to your computer when you connect to the Internet. Each time you visit this Website, our web server may automatically recognize and collect this information.') }} </p>
            <p>{{ __("content.Automatic information also includes 'cookies' and 'web beacons. ' A 'cookie' is a small amount of data that is sent to your browser from a web server and stored on your computer's hard drive. Among other things, cookies provide a means for us to keep track of your online patterns and preferences. By understanding which areas of the website you visit, cookies allow us to present information, products and services that are of personal interest. A cookie will not allow us to learn any personal information (such as your real name and address) that you have not otherwise disclosed. Most browsers are initially set up to accept cookies. You can change your browser so that it will not automatically accept cookies. However, if you do so, it is possible that some portions of the Website may not function as intended. 'Web beacons', also known as clear GIFs or single-pixel GIFs, are small image files that we may place on web pages within this Website and within web-based email newsletters that we send. Working in conjunction with cookies, web beacons allow us to accurately count the number of unique users who have visited a specific web page and the number of times those web pages are displayed. We can also use web beacons to let us know how many people opened a web-based email newsletter.") }} </p>
            <p>{{ __('content.We may associate automatic information with your personal information. In the event of such association, such automatic information will be considered personal information.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.HOW DOES SANDRO USE THIS INFORMATION?') }} </h4>
            <p>{{ __('content.Sandro uses this information to provide the products and services that you have ordered or requested, to confirm, process and ship sales transactions, to send order and shipping confirmations, to contact you with questions or communications about your order, or to respond to your customer service inquiries.') }} </p>
            <p>{{ __('content.Sandro also uses this information to enhance and personalize your shopping experience, both online and in our stores, to communicate with you for marketing and promotional purposes (including via targeted postal pieces, phone messages, newsletters, or emails); to gauge the effectiveness of such promotional communications; to administer, analyze, and improve the effectiveness of our Website; to document our business activities; and for archival and record retention purposes.') }} </p>
            <p>{{ __('content.We do not want to receive confidential or proprietary information or trade secrets through this Website. Any such information, materials, suggestions, ideas or comments sent to us will be deemed non-confidential, and by submitting it, you are granting us an irrevocable and unrestricted license to use, modify, reproduce, transmit, display and distribute it for any purpose whatsoever, with no payment or other compensation to you.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.HOW CAN YOU ACCESS YOUR INFORMATION?') }} </h4>
            <p>{{ __('content.You may access and edit the personal information that is stored in your user account on this Website by signing or logging in on the Website. Simply click on the "Sign In" or "My Account " link from the home page and enter your email address and password to access your information. You can request password help at any time by clicking on the "Reset password" link at which time we will email you a secure link to change your password to the associated email address. Currently, we do not provide online access to information that you provided to Sandro offline, for example at stores. You may also request to access, correct or delete personal information that you have provided to us at any time from our customer service representatives or by contacting us using the contact information below.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.HOW DOES MICAHHA PROTECT YOUR INFORMATION?') }} </h4>
            <p>{{ __('content.We have implemented appropriate physical, electronic and administrative measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration and disclosure. When you place an order on the Website, Secure Socket Layer Technology ("SSL") encryption technology is utilized to protect your personal information during data transport. Please note that e-mail is not encrypted and is not considered to be a secure means of transmitting credit card information. While we strive to protect your personal information, we cannot guarantee or warrant that such information, during transmission through the Internet or while stored on our system or otherwise in our care, as the case may be, will be completely secure. Therefore, the provision of such information is done at your own risk. We shall have no liability for disclosure of your personal information due to errors, omissions or unauthorized acts of third parties during or after transmission.') }} </p>
            <p>{{ __('content.When you create an online account on the Website and become a registered user, you will be asked to provide an accurate email address and create a password. You are responsible for keeping this password confidential and are urged (i) not to share your password or account information with others, (ii) to use a secure web browser, and (iii) to change your password from time to time. If you wish to cancel a password, or if you become aware of any loss, theft, or unauthorized use of a password, please contact us as set forth below.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.DOES MICAHHA DISCLUSE YOUR INFORMATION TO OTHERS?') }} </h4>
            <p>{{ __('content.All of the information that Sandro collects may be shared among our subsidiaries and affiliates. Sandro maintains a central database of customer information collected by online and from offline sources. When you establish or update your customer profile information with Sandro, whether through a purchase, becoming a registered user of the Website, modifying your online account, or signing-up for promotional materials at the Website, our stores, through a customer service representative, or in any other communication you may have with us, we will update your customer profile information on the database.') }} </p>
            <p>{{ __('content.Except as otherwise described in this Privacy Policy, Sandro does not sell, rent or trade with third parties any personal information you provide to us online or at our stores, nor do we share such information with third parties. We may disclose personal information about you to third party service providers that act on our behalf and who agree to maintain the confidentiality of such information in accordance with this Privacy Policy and use the information only in connection with the services they provide. These third parties may provide a variety of services to us including, without limitation, processing credit card payments, providing website hosting and services related to storage and/or analysis of data, fraud protection and credit risk reduction, assisting us in fulfilling your transactions and customer service inquiries, updating your customer profile information in the database, marketing and promotional material distribution, assisting in data collection, or fulfilling your request to unsubscribe from our emails, newsletters and/or other promotional materials. We do not authorize such third party service providers to make any other use of your information.') }} </p>
            <p>{{ __('content.We may use and/or disclose to others aggregate information about your demographics and use of our Website in a manner that does not reveal your identity.') }} </p>
            <p>{{ __('content.We may disclose personal information in special cases when we have reason to believe that disclosing this information is necessary to identify, contact, or bring legal action against someone who may have breached our Terms of Use or who may be causing injury to or interference with (either intentionally or unintentionally) our rights or property, or those of other users of our Website, or anyone else who could be harmed by such activities. We may also disclose personal information when we reasonably believe that the law requires us to do so.') }} </p>
            <p>{{ __('content.We may transfer or disclose personal information in the event that Sandro and/or its subsidiaries or affiliates engages in a business transition, such as a merger, acquisition by another company, the sale of a business unit or assets, or other "change of control " transaction. In such transactions, personal information generally is one of the transferred business assets but remains subject to the promises made in any pre-existing privacy policy.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.CAN I UNSUBSCRIBE?') }} </h4>
            <p>{{ __('content.Yes. Sandro honours requests to unsubscribe or "opt-out " from receipt of emails, newsletters and/or other promotional materials (including for emails that we permit other companies to send to their own list of customers or subscribers). There are several ways in which you can tell us whether or not you want to unsubscribe or "opt-out " from receiving promotional communications from us or from certain uses of your personal information. For example, (1) in emails you receive from us, you will have the opportunity to unsubscribe or "opt-out " from receiving future promotional emails from us, or (2) when you become a registered user of the Website or when you access your online account thereafter, you may have the opportunity to make or change your selections in this regard. Please note that you may continue to receive emails, newsletters and/or other promotional materials from Sandro and/or its subsidiaries or affiliates until such requests become effective, we will endeavor to respond to such requests as soon as practicable. In the event you unsubscribe or "opt-out " from receiving promotional correspondence from us, we may still contact you in connection with your relationship with us, Website-related orders or transactions, and related communications with us.') }} </p>
         </div>
         <div>
            <h4>{{ __('content.LINKS TO OTHER WEBSITES') }} </h4>
            <p>{{ __('content.While you are using this Website, you may be linked or directed to websites not operated by Sandro, including separate websites operated by our affiliates or by unaffiliated third parties. For example, you might click on a link or banner ad that will take you from the Website to the website(s) of social networks (such as Facebook or Twitter), advertisers, sponsors or co-branding partners. Sandro does not control websites that are operated by these persons and is not responsible for the information practices of such websites or the acts or omissions of such website\u2019s operators. Please review the privacy policies of such websites and be advised that the practices described in this Privacy Policy do not reflect the practices regarding information collection, use and disclosure of linked websites or the owners or operators of those linked websites. For more information, please read our Terms of Use') }} </p>
         </div>
         <div>
            <h4>{{ __('content.CONTACT INFORMATION') }} </h4>
            <p>{{ __('content.We welcome your comments regarding this privacy policy. Please send any concerns by email to customercare@sandro-paris.com.au or by mail to:') }} </p>
            <p> <a href="mailto:enquiry@micahha.com"> enquiry@micahha.com </a> </p>
            <p>{{ __('content.C/- International Fashion Brands') }} <br/>{{ __('content.Suite 301, 30-36 Bay Street') }} <br/>{{ __('content.Double Bay NSW 2028 Australia') }} </p>
         </div>
      </div>
   </div>
</section>

@endsection